jobs:
build:

  runs-on: windows-latest

   steps:
      - name: Check-out repository
      uses: actions/checkout@v3

      - name: Setup Python
      uses: actions/setup-python@v4
      with:
         python-version: '3.11.6'
         cache: 'pip'
         cache-dependency-path: |
            **/requirements*

      - name: Install your Dependencies
      run: |
         pip install -r requirements -r requirements-dev

      - name: Build Executable with Nuitka
      uses: Nuitka/Nuitka-Action@main
      with:
         nuitka-version: main
         script-name: main.py
         # many more Nuitka options available, see action doc, but it's best
         # to use nuitka-project: options in your code, so e.g. you can make
         # a difference for macOS and create an app bundle there.
         onefile: true

      - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
         name: Windows Build
         path: | # match what's created for the 3 OSes
            build/*.exe